name: git-action-test

#  github 内新建一个tag
on:
  push:
    tags:
      - 'v*'

jobs:
  npm_publish:
    # name: 在 Github 中显示的 job 名称
    name: buildLibrary
    runs-on: ubuntu-latest
    steps:
      # name:  当前 step 的名字
    - name: Checkout    # 获取分支的代码和提交记录
      uses: actions/checkout@v2

    - name: Setup Node.js v14.x # 设置 Node.js 的环境
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

      # - name: Install
      #   run: npm install # 安装依赖

      # - name: Build
      #   run: npm run build
      # 执行部署
  # publish    
    - name: Publish
      uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/  # 设置发包npm地址仓库
      run: npm publish # 执行发布
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}} # 刚刚设置的 NPM_TOKE
  