name: git-action-test

#  github 内新建一个tag
on:
  push:
    tags:
      - 'v*'

jobs:
  npm_publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout    # 获取分支的代码和提交记录
      uses: actions/checkout@v2

    - name: Setup Node.js v14.x # 设置 Node.js 的环境
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Publish
    - run: npm publish # 执行发布
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}} # 刚刚设置的 NPM_TOKE
